Latest GraalVM github action changes
micronaut-projects/github-actions pull request #32
Opened 2023-07-06 09:08 UTC by msupic

The changes from this PR are already used in the `micronaut-project-template` graalvm workflows (for example, [graalvm-dev.yml](https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/graalvm-dev.yml) is using `build-matrix@latest-graalvm-changes` task). Since all micronaut projects have been synced with `micronaut-project-template` workflows, we can push changes from this branch to the master branch and then modify workflows in the micronaut-project-template (replace `build-matrix@latest-graalvm-changes` with `build-matrix@master`, `pre-build@latest-graalvm-changes` with `pre-build@master`.

**Important**: Since we need to keep the `latest-graalvm-changes` branch until `micronaut-project-template` graalvm workflows start using github actions from the `master` branch, I created `latest-graalvm-changes-2` from `latest-graalvm-changes` so `latest-graalvm-changes` doesn't get deleted when pushing these changes to the `master` branch.

2023-07-24 13:33 UTC, sdelamo requested changes

2023-07-24 13:33 UTC, sdelamo commented on graalvm/build-matrix/action.yml
> +      uses: graalvm/setup-graalvm@v1
don't p `@v1` use a fully qualified version number.

2023-07-24 13:33 UTC, sdelamo commented on graalvm/pre-build/action.yml
> +      uses: graalvm/setup-graalvm@v1
don't p `@v1` use a fully qualified version number.

2023-07-24 14:05 UTC, msupic commented on graalvm/build-matrix/action.yml
> +      uses: graalvm/setup-graalvm@v1
Replaced with v1.1.1

2023-07-24 14:05 UTC, msupic commented on graalvm/pre-build/action.yml
> +      uses: graalvm/setup-graalvm@v1
Replaced with v1.1.1

2023-07-26 11:31 UTC, sdelamo approved these changes

2023-07-26 11:31 UTC, merged